import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "/usr/bin/zsh"
args = ["-c", "tmux", "new", "-As0"]

[env]
TERM = "screen-256color"

[window]
opacity = 0.9
blur = true

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 10

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Right", mods = "Control", action = "Paste" },
]
