#!/bin/bash
# https://erfur.github.io/2021/11/20/fzf_as_dmenu.html

# --print-query is used to run a custom command when none of the list is
# selected with ctrl-space.
OPTS='--info=inline --print-query --bind=ctrl-space:print-query,tab:replace-query'

exec i3-msg -q "exec --no-startup-id $(compgen -c | fzf $OPTS | tail -1)"
