#! /usr/bin/bash

# lesspipe.sh doesn't use eza, bat, or chafa; it uses ls and exiftool instead. So, we create a lessfilter.

dim=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}
if [[ $dim = x ]]; then
  dim=$(stty size < /dev/tty | awk '{print $2 "x" $1}')
elif ! [[ $KITTY_WINDOW_ID ]] && (( FZF_PREVIEW_TOP + FZF_PREVIEW_LINES == $(stty size < /dev/tty | awk '{print $1}') )); then
  # Avoid scrolling issue when the Sixel image touches the bottom of the screen
  # * https://github.com/junegunn/fzf/issues/2544
  dim=${FZF_PREVIEW_COLUMNS}x$((FZF_PREVIEW_LINES - 1))
fi

mime=$(file -bL --mime-type "$1")
category=${mime%%/*}
kind=${mime##*/}

if [[ -d "$1" || -L "$1" && "$category" = inode/directory ]]; then
  eza -1 --git --color=always --icons "$1"
elif [ "$category" = image ]; then
  kitty icat --clear --transfer-mode=memory --unicode-placeholder --stdin=no --place="$dim@0x0" "$1" | sed '$d' | sed $'$s/$/\e[m/'
  exiftool "$1" | bat --color=always -plyaml
elif [ "$kind" = vnd.openxmlformats-officedocument.spreadsheetml.sheet ] ||	[ "$kind" = vnd.ms-excel ]; then
  in2csv "$1" | xsv table | bat -ltsv --color=always
elif [ "$category" = text ]; then
  if [[ "$1" == *.md ]]; then
    mdcat -l "$1"
  else
    bat --color=always "$1"
  fi
else
  lesspipe.sh "$1" | bat --color=always
fi
