#! /usr/bin/bash

mime=$(file -bL --mime-type "$1")
category=${mime%%/*}
kind=${mime##*/}
if [[ -d "$1" || -L "$1" && "$category" = inode/directory ]]; then
	exa -1 --git --color=always --icons "$1"
elif [ "$category" = image ]; then
	chafa "$1"
	exiftool "$1"
elif [ "$kind" = vnd.openxmlformats-officedocument.spreadsheetml.sheet ] || \
	[ "$kind" = vnd.ms-excel ]; then
	in2csv "$1" | xsv table | bat -ltsv --color=always
elif [ "$category" = text ]; then
  if [[ "$1" == *.md ]]; then
    mdcat -l "$1"
  else
    bat --color=always "$1"
  fi
else
	lesspipe.sh "$1" | bat --color=always
fi
# lesspipe.sh don't use exa, bat and chafa, it use ls and exiftool. so we create a lessfilter.

